import type { JobPrediction, TrialJob, V4FlowState } from "./types";

export const curatedJobs: Array<TrialJob & { prediction: JobPrediction }> = [
  {
    id: "ai_pm",
    title: "AI 产品经理",
    company: "精品岗位副本",
    city: "通用场景",
    salary: "校招 / 实习",
    description: "围绕用户需求、AI 能力边界、产品方案和效果指标完成一次真实产品决策。",
    image: "job-product-manager.png",
    keywords: ["需求分析", "用户洞察", "AI 理解", "方案设计"],
    sourceName: "职前副本精品岗位",
    sourceUrl: "",
    jdText: "负责 AI 产品的需求分析、功能设计、用户反馈整理和效果优化。",
    prediction: {
      interest: 92,
      pressure: 68,
      achievement: 90,
      fit: 82,
      evidence: ["用户材料显示偏好解决开放问题", "具备用户洞察与结构化表达基础", "对成果落地有较高成就需求"],
      uncertainties: ["数据分析深度尚未被真实任务验证", "需求快速变化时的压力反应仍需校准"],
    },
  },
  {
    id: "new_media",
    title: "新媒体运营",
    company: "精品岗位副本",
    city: "通用场景",
    salary: "校招 / 实习",
    description: "围绕内容策划、用户增长、热点判断和数据复盘完成一次运营任务。",
    image: "job-content-operations.png",
    keywords: ["内容策划", "用户增长", "热点判断", "数据复盘"],
    sourceName: "职前副本精品岗位",
    sourceUrl: "",
    jdText: "负责内容策划、账号运营、用户增长和传播效果复盘。",
    prediction: {
      interest: 86,
      pressure: 74,
      achievement: 84,
      fit: 79,
      evidence: ["沟通表达与用户感知能力较强", "喜欢创意与快速反馈", "具备基础内容组织能力"],
      uncertainties: ["持续高频内容输出是否造成消耗", "对热点节奏的长期适应度未知"],
    },
  },
  {
    id: "data_analyst",
    title: "数据分析师",
    company: "精品岗位副本",
    city: "通用场景",
    salary: "校招 / 实习",
    description: "围绕业务问题完成指标定义、数据判断、可视化结论与行动建议。",
    image: "job-data-analyst.png",
    keywords: ["数据清洗", "业务洞察", "可视化", "SQL"],
    sourceName: "职前副本精品岗位",
    sourceUrl: "",
    jdText: "负责数据清洗、指标分析、可视化和业务决策支持。",
    prediction: {
      interest: 80,
      pressure: 62,
      achievement: 82,
      fit: 76,
      evidence: ["逻辑分析能力与岗位要求一致", "对数据驱动决策有明显偏好", "愿意深入研究问题"],
      uncertainties: ["SQL 与建模能力需要任务验证", "是否享受长时间独立分析仍不确定"],
    },
  },
];

export const defaultFlowState: V4FlowState = {
  trialSource: "curated",
  selectedJob: null,
  selectedSearchJob: null,
  prediction: null,
  mission: null,
  submission: { text: "", attachments: [], submittedAt: "" },
  evaluation: null,
  reflection: { interest: 82, pressure: 60, achievement: 84, continueIntent: 80, note: "" },
  report: null,
  calibrationProposal: [],
  calibratedAt: "",
  history: [],
  learningPlan: null,
};
